language: java
jdk:
- oraclejdk7
env:
  global:
  - MONGO_HOST=oceanic.mongohq.com
  - MONGO_PORT=10035
  - MONGO_USERNAME=travis-test
  - MONGO_DB=fishkeesTest
  - secure: eSKuWVDtYDwyW9fNH/4ESwAPHcj4ZwkY4cNggL9nysdMiD+/26bgGm4WNrcEm8bJ/+VJZOtgaQp4TeDThIsBM3ywAU3TjFrkhSA67O8m07gkbxjPg7EF8nJ4joaVEZXBVYxYGTNMZTHdjGwXGChV6UCc9yld/F2x49mlcZXiVyI=
  - secure: VdqtZnJs0nI2LAPUoPUSL4PY96wkayML1Ub2Vf1hTyXQ6SCkLWpAsBsFWjAUn5uVdH4gW376uqYz8p1LBXB25h2eZRLGlkSH68OqXqG4Zf+pM0VeIZp8K5DnCVG51+CCJYmYjvP8830KgpzfmiBLvEmWOqKVCCnBhogkrMFshQM=
script: mvn verify -q
deploy:
  provider: heroku
  api_key:
    secure: CoTR27DFVTVsJoL8JGQBJhyWg9iQY/k6Kp+zTDqUyccPD+LajhicIgqUQ4jtbGtWLKHJq0P477zaif+ZfhckgUyYW+W/2drHGw0l8OUmvKrqBUacTJ4004Ikwq853ky2u8MXT0zYWhiNzF/8I+Nss7vME8OHuJE8oaGX0aHBrvg=
  app: fishkees-demo
  on:
    repo: mhaligowski/fishkees-backend
    branch: master
